RecipeBox/ViewModels/SearchResults.cs
using RecipeBox.Models;
namespace RecipeBox.ViewModels
{
public class SearchResults
{
    public List<Recipe> RecipeResults { get; set; }
    public List<Ingredient> IngredientResults { get; set; }
}
}

RecipeBox/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using RecipeBox.Models;
using RecipeBox.ViewModels;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;
using RestSharp;
using Microsoft.Extensions.Configuration;


namespace RecipeBox.Controllers
{
public class HomeController : Controller
{
    private readonly RecipeBoxContext _db;
    private readonly string _apiKey;
    private readonly UserManager<ApplicationUser> _userManager;

    public HomeController(UserManager<ApplicationUser> userManager, RecipeBoxContext db, IConfiguration configuration)
    {
        _userManager = userManager;
        _db = db;
        _apiKey = configuration["MealDb"];
    }

    [HttpGet("/")]
    public async Task<ActionResult> Index()
    {
        Ingredient[] ingredients = _db.Ingredients.ToArray();
        Dictionary<string, object[]> model = new Dictionary<string, object[]>();
        string userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
        ApplicationUser currentUser = await _userManager.FindByIdAsync(userId);
        if (currentUser != null)
        {
            Recipe[] recipes = _db.Recipes.Where(entry => entry.User.Id == currentUser.Id).ToArray();
            model.Add("recipes", recipes);
            model.Add("ingredients", ingredients);
            return View(model);
        }
        else
        {
            model.Add("recipes", new Recipe[1]);
            model.Add("ingredients", new Ingredient[1]);
            return View(model);
        }
        
    }

    public ActionResult Search(string searchTerm)
    {
        List<Recipe> recipeResults = _db.Recipes
            .Where(recipe => recipe.Name.Contains(searchTerm) || recipe.Instruction.Contains(searchTerm))
            .ToList();

        List<Ingredient> ingredientResults = _db.Ingredients
            .Where(ingredient => ingredient.IngredientName.Contains(searchTerm))
            .ToList();

        var searchResults = new SearchResults
        {
            RecipeResults = recipeResults,
            IngredientResults = ingredientResults
        };

        return View("SearchResults", searchResults);
    }

    public async Task<IActionResult> MealOfTheDay()
    {
        RandomMeal meal = await RandomMeal.GetMeal(_apiKey);
    return View("MealOfTheDay", meal);
    }

}
}

RecipeBox/Controllers/IngredientController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using RecipeBox.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

namespace RecipeBox.Controllers
{
  public class IngredientsController : Controller
  {
    private readonly RecipeBoxContext _db;

    public IngredientsController(RecipeBoxContext db)
    {
      _db = db;
    }
    public ActionResult Index()
    {
        List<Ingredient> model = _db.Ingredients.ToList();
      return View(model);
    }
    [Authorize]
    public ActionResult Create()
    {
      ViewBag.RecipeId = new SelectList(_db.Recipes, "RecipeId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Ingredient ingredient)
    {
      _db.Ingredients.Add(ingredient);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Ingredient thisIngredient = _db.Ingredients.Include(ingredient => ingredient.JoinEntities).ThenInclude(join => join.Recipe).FirstOrDefault(ingredient => ingredient.IngredientId == id);
      return View(thisIngredient);
    }
    [Authorize]
    public ActionResult Edit(int id)
    {
      Ingredient thisIngredient = _db.Ingredients.FirstOrDefault(ingredient => ingredient.IngredientId == id);
      ViewBag.RecipeId = new SelectList(_db.Recipes, "RecipeId", "Name");
      return View(thisIngredient);
    }

    [HttpPost]
    public ActionResult Edit(Ingredient ingredient)
    {
      _db.Ingredients.Update(ingredient);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    [Authorize]
    public ActionResult Delete(int id)
    {
      Ingredient thisIngredient = _db.Ingredients.FirstOrDefault(ingredient => ingredient.IngredientId == id);
      return View(thisIngredient);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Ingredient thisIngredient = _db.Ingredients
                           .FirstOrDefault(ingredient => ingredient.IngredientId == id);
      _db.Ingredients.Remove(thisIngredient);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    [Authorize]
    public ActionResult AddRecipe(int id)
    {
      Ingredient thisIngredient = _db.Ingredients.FirstOrDefault(ingredient => ingredient.IngredientId == id);
      ViewBag.RecipeId = new SelectList(_db.Recipes, "RecipeId", "Name");
      return View(thisIngredient);
    }

    [HttpPost]
    public ActionResult AddRecipe(Ingredient ingredient, int recipeId)
    {
#nullable enable
      RecipeIngredient? joinEntity = _db.RecipeIngredients.FirstOrDefault(join => (join.IngredientId == ingredient.IngredientId && join.RecipeId == recipeId));
#nullable disable

      if (joinEntity == null && ingredient.IngredientId != 0)
      {
        _db.RecipeIngredients.Add(new RecipeIngredient() { IngredientId = ingredient.IngredientId, RecipeId = recipeId });
        _db.SaveChanges();
      }
      return RedirectToAction("Details", new { id = ingredient.IngredientId });
    }
    [Authorize]
        [HttpPost]
    public ActionResult DeleteJoin(int joinId)
    {
      RecipeIngredient joinEntry = _db.RecipeIngredients.FirstOrDefault(entry => entry.RecipeIngredientId == joinId);
      _db.RecipeIngredients.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    } 
  }

}

RecipeBox/Controllers/RecipeController.cs
using Microsoft.AspNetCore.Authorization;
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using RecipeBox.Models;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;


namespace RecipeBox.Controllers
{
    [Authorize]
    public class RecipesController : Controller
    {
        private readonly RecipeBoxContext _db;
        private readonly UserManager<ApplicationUser> _userManager;

        public RecipesController(UserManager<ApplicationUser> userManager, RecipeBoxContext db)
        {
            _userManager = userManager;
            _db = db;
        }
        public async Task<ActionResult> Index()
        {
            string userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            ApplicationUser currentUser = await _userManager.FindByIdAsync(userId);
            List<Recipe> userRecipes = _db.Recipes.Where(entry => entry.User.Id == currentUser.Id).Include(recipe => recipe.JoinEntities).ToList();
            return View(userRecipes);
        }
        [Authorize]
        public ActionResult Create()
        {
            ViewBag.IngredientId = new SelectList(_db.Ingredients, "IngredientId", "IngredientName");
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create(Recipe recipe, int IngredientId)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.IngredientId = new SelectList(_db.Ingredients, "IngredientId", "IngredientName");
                return View(recipe);
            }
            else
            {
                string userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
                ApplicationUser currentUser = await _userManager.FindByIdAsync(userId);
                recipe.User = currentUser;
                _db.Recipes.Add(recipe);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
        }

        public ActionResult Details(int id)
        {
            Recipe thisRecipe = _db.Recipes.Include(recipe => recipe.JoinEntities).ThenInclude(join => join.Ingredient).Include(recipe => recipe.JoinTags).ThenInclude(join => join.Tag).FirstOrDefault(recipe => recipe.RecipeId == id);
            return View(thisRecipe);
        }
        [Authorize]
        public ActionResult Edit(int id)
        {
            Recipe thisRecipe = _db.Recipes.FirstOrDefault(recipe => recipe.RecipeId == id);
            ViewBag.IngredientId = new SelectList(_db.Ingredients, "IngredientId", "IngredientName");
            return View(thisRecipe);
        }

        [HttpPost]
        public ActionResult Edit(Recipe recipe)
        {
            _db.Recipes.Update(recipe);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
        [Authorize]
        public ActionResult Delete(int id)
        {
            Recipe thisRecipe = _db.Recipes.FirstOrDefault(recipe => recipe.RecipeId == id);
            return View(thisRecipe);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Recipe thisRecipe = _db.Recipes
                                 .FirstOrDefault(recipe => recipe.RecipeId == id);
            _db.Recipes.Remove(thisRecipe);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
        [Authorize]
        public ActionResult AddIngredient(int id)
        {
            Recipe thisRecipe = _db.Recipes.FirstOrDefault(recipe => recipe.RecipeId == id);
            ViewBag.IngredientId = new SelectList(_db.Ingredients, "IngredientId", "IngredientName");
            return View(thisRecipe);
        }

        [HttpPost]
        public ActionResult AddIngredient(Recipe recipe, int ingredientId)
        {
#nullable enable
            RecipeIngredient? joinEntity = _db.RecipeIngredients.FirstOrDefault(join => (join.RecipeId == recipe.RecipeId && join.IngredientId == ingredientId));
#nullable disable

            if (joinEntity == null && recipe.RecipeId != 0)
            {
                _db.RecipeIngredients.Add(new RecipeIngredient() { RecipeId = recipe.RecipeId, IngredientId = ingredientId });
                _db.SaveChanges();
            }
            return RedirectToAction("Details", new { id = recipe.RecipeId });
        }
        [Authorize]
        [HttpPost]
        public ActionResult DeleteIngredient(int joinId)
        {
            RecipeIngredient joinEntry = _db.RecipeIngredients.FirstOrDefault(entry => entry.RecipeIngredientId == joinId);
            _db.RecipeIngredients.Remove(joinEntry);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
        [Authorize]
        public ActionResult AddTag(int id)
        {
            Recipe thisRecipe = _db.Recipes.FirstOrDefault(recipe => recipe.RecipeId == id);
            ViewBag.TagId = new SelectList(_db.Tags, "TagId", "Title");
            return View(thisRecipe);
        }

        [HttpPost]
        public ActionResult AddTag(Recipe recipe, int tagId)
        {
#nullable enable
            RecipeTag? joinEntity = _db.RecipeTags.FirstOrDefault(join => (join.RecipeId == recipe.RecipeId && join.TagId == tagId));
#nullable disable

            if (joinEntity == null && recipe.RecipeId != 0)
            {
                _db.RecipeTags.Add(new RecipeTag() { RecipeId = recipe.RecipeId, TagId = tagId });
                _db.SaveChanges();
            }
            return RedirectToAction("Details", new { id = recipe.RecipeId });
        }

        public ActionResult AddUser(int id)
        {
            Recipe thisRecipe = _db.Recipes.FirstOrDefault(recipe => recipe.RecipeId == id);
            ViewBag.Id = new SelectList(_db.AspNetUsers, "Id", "UserName");
            return View(thisRecipe);
        }
        [HttpPost]
        public async Task<ActionResult> AddUser(Recipe recipe, string id)
        {
#nullable enable
            ApplicationUser currentUser = await _userManager.FindByIdAsync(id);
            RecipeUser? joinEntity = _db.RecipeUser.FirstOrDefault(join => (join.RecipeId == recipe.RecipeId && join.User.Id == id));
#nullable disable

            if (joinEntity == null && recipe.RecipeId != 0)
            {
                _db.RecipeUser.Add(new RecipeUser() { RecipeId = recipe.RecipeId, User = currentUser });
                _db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        public async Task<ActionResult> SharedRecipes()
        {
            string userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            List<RecipeUser> sharedRecipes = _db.RecipeUser.Where(entry => entry.User.Id == userId).Include(recipe => recipe.Recipe).ToList();
            return View(sharedRecipes);
        }
    }
}

RecipeBox/Controllers/TagController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RecipeBox.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace RecipeBox.Controllers
{
  public class TagsController : Controller
  {
    private readonly RecipeBoxContext _db;

    public TagsController(RecipeBoxContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      return View(_db.Tags.ToList());
    }

    public ActionResult Details(int id)
    {
      Tag thisTag = _db.Tags
          .Include(tag => tag.JoinTags)
          .ThenInclude(join => join.Recipe)
          .FirstOrDefault(tag => tag.TagId == id);
      return View(thisTag);
    }
    [Authorize]
    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Tag tag)
    {
      _db.Tags.Add(tag);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    [Authorize]
    public ActionResult AddRecipe(int id)
    {
      Tag thisTag = _db.Tags.FirstOrDefault(tags => tags.TagId == id);
      ViewBag.RecipeId = new SelectList(_db.Recipes, "RecipeId", "Name");
      return View(thisTag);
    }

    [HttpPost]
    public ActionResult AddRecipe(Tag tag, int recipeId)
    {
      #nullable enable
      RecipeTag? joinTags = _db.RecipeTags.FirstOrDefault(join => (join.RecipeId == recipeId && join.TagId == tag.TagId));
      #nullable disable
      if (joinTags == null && recipeId != 0)
      {
        _db.RecipeTags.Add(new RecipeTag() { RecipeId = recipeId, TagId = tag.TagId });
        _db.SaveChanges();
      }
      return RedirectToAction("Details", new { id = tag.TagId });
    }
    [Authorize]
    public ActionResult Edit(int id)
    {
      Tag thisTag = _db.Tags.FirstOrDefault(tags => tags.TagId == id);
      return View(thisTag);
    }

    [HttpPost]
    public ActionResult Edit(Tag tag)
    {
      _db.Tags.Update(tag);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    [Authorize]
    public ActionResult Delete(int id)
    {
      Tag thisTag = _db.Tags.FirstOrDefault(tags => tags.TagId == id);
      return View(thisTag);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Tag thisTag = _db.Tags.FirstOrDefault(tags => tags.TagId == id);
      _db.Tags.Remove(thisTag);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    
    [Authorize]
    [HttpPost]
    public ActionResult DeleteJoin(int joinId)
    {
      RecipeTag joinEntry = _db.RecipeTags.FirstOrDefault(entry => entry.RecipeTagId == joinId);
      _db.RecipeTags.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

RecipeBox/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}

@using RecipeBox.Models;
@{
    
    Random random = new Random();
    int randomNumber = random.Next(1, 999);
}


<h1>Welcome to the Recipe Box!</h1>
<h3>@Html.ActionLink("Recipe Roulette", "MealOfTheDay")</h3>
<img src="https://baconmockup.com/@randomNumber/@randomNumber" alt="MEAT" />

<hr>

<h4>Recipes</h4>
@if (User.Identity.IsAuthenticated)
{
  @if (Model["recipes"].Length == 0)
  {
    <p>No recipes have been added yet!</p>
  } 
  <ul>
    @foreach (Recipe recipe in Model["recipes"])
    {
      <li>@Html.ActionLink(@recipe.Name, "Details", "Recipes", new { id = @recipe.RecipeId})</li>
    }
  </ul>
}

@if (User.Identity.IsAuthenticated)
{
  <h4>Ingredients for @User.Identity.Name</h4>
  @if (Model["ingredients"].Length == 0)
  {
    <p>No ingredients have been added yet!</p>
  } 
  <ul>
    @foreach (Ingredient ingredient in Model["ingredients"])
    {
      <li>@Html.ActionLink(@ingredient.IngredientName, "Details", "Ingredients", new { id = @ingredient.IngredientId})</li>
    }
  </ul>
}
else
{
  <h4>Ingredients</h4>
  <p>Please @Html.ActionLink("log in", "LogIn", "Account") to view or manage your ingredients.</p>
}

<hr>

<p>@Html.ActionLink("Manage Recipes", "Index", "Recipes")</p> 
<p>@Html.ActionLink("Manage Ingredients", "Index", "Ingredients")</p>
<p>@Html.ActionLink("Manage Tags", "Index", "Tags")</p>
<p>@Html.ActionLink("Create or manage an account", "Index", "Account")</p>

RecipeBox/Views/Home/MealOfTheDay.cshtml
@{
    Layout = "_Layout";
}
@using RecipeBox.Models

    @{
    
    Random random = new Random();
    int randomNumber = random.Next(1, 999);
}

<h3>@Html.ActionLink("Recipe Roulette", "MealOfTheDay")</h3>
<img src="https://baconmockup.com/@randomNumber/@randomNumber" alt="MEAT" />
    <h1>@Model.strMeal</h1>
    <ul>
        <li>@Model.strMeasure1 @Model.strIngredient1</li>
        <li>@Model.strMeasure2 @Model.strIngredient2</li>
        <li>@Model.strMeasure3 @Model.strIngredient3</li>
        <li>@Model.strMeasure4 @Model.strIngredient4</li>
        <li>@Model.strMeasure5 @Model.strIngredient5</li>
        <li>@Model.strMeasure6 @Model.strIngredient6</li>
        <li>@Model.strMeasure7 @Model.strIngredient7</li>
        <li>@Model.strMeasure8 @Model.strIngredient8</li>
        <li>@Model.strMeasure9 @Model.strIngredient9</li>
        <li>@Model.strMeasure10 @Model.strIngredient10</li>
        <li>@Model.strMeasure11 @Model.strIngredient11</li>
        <li>@Model.strMeasure12 @Model.strIngredient12</li>
        <li>@Model.strMeasure13 @Model.strIngredient13</li>
        <li>@Model.strMeasure14 @Model.strIngredient14</li>
        <li>@Model.strMeasure15 @Model.strIngredient15</li>
        <li>@Model.strMeasure16 @Model.strIngredient16</li>
        <li>@Model.strMeasure17 @Model.strIngredient17</li>
        <li>@Model.strMeasure18 @Model.strIngredient18</li>
        <li>@Model.strMeasure19 @Model.strIngredient19</li>
        <li>@Model.strMeasure20 @Model.strIngredient20</li>
    </ul>
    <br>
    <br>
    <p>@Model.strInstructions</p>

<p>@Html.ActionLink("Home", "Index")</p>

RecipeBox/Views/Home/SearchResults.cshtml
@{
  Layout = "_Layout";
}
@using RecipeBox.ViewModels;
@model RecipeBox.ViewModels.SearchResults;

<h2>Search Results</h2>

@if (Model.RecipeResults.Count == 0 && Model.IngredientResults.Count == 0)
{
    <p>No results found for the search term.</p>
}
else
{
    @if (Model.RecipeResults.Count > 0)
    {
        <h3>Recipe Results</h3>
        <ul>
            @foreach (var recipe in Model.RecipeResults)
            {
                <li>
                    @Html.ActionLink(recipe.Name, "Details", "Recipes", new { id = recipe.RecipeId }, null)
                </li>
            }
        </ul>
    }

    @if (Model.IngredientResults.Count > 0)
    {
        <h3>Ingredient Results</h3>
        <ul>
            @foreach (var ingredient in Model.IngredientResults)
            {
                <li>@Html.ActionLink(ingredient.IngredientName, "Details", "Ingredients", new { id = ingredient.IngredientId})</li>
                <p>@Html.ActionLink("Home", "Index")</p>
            }
        </ul>
    }
}